package bpm_vvg.sluzbazakorisnike;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Korisnik implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("MSISDN")
   private java.lang.Integer MSISDN;

   @org.kie.api.definition.type.Label("OIB")
   private java.lang.String OIB;

   @org.kie.api.definition.type.Label("Datum rodenja")
   private java.util.Date datumRodenja;

   @org.kie.api.definition.type.Label("Ime Korisnika")
   private java.lang.String imeKorisnika;

   @org.kie.api.definition.type.Label(value = "Prezime Korisnika")
   private java.lang.String prezimeKorisnika;

   public Korisnik()
   {
   }

   public java.lang.Integer getMSISDN()
   {
      return this.MSISDN;
   }

   public void setMSISDN(java.lang.Integer MSISDN)
   {
      this.MSISDN = MSISDN;
   }

   public java.lang.String getOIB()
   {
      return this.OIB;
   }

   public void setOIB(java.lang.String OIB)
   {
      this.OIB = OIB;
   }

   public java.util.Date getDatumRodenja()
   {
      return this.datumRodenja;
   }

   public void setDatumRodenja(java.util.Date datumRodenja)
   {
      this.datumRodenja = datumRodenja;
   }

   public java.lang.String getImeKorisnika()
   {
      return this.imeKorisnika;
   }

   public void setImeKorisnika(java.lang.String imeKorisnika)
   {
      this.imeKorisnika = imeKorisnika;
   }

   public java.lang.String getPrezimeKorisnika()
   {
      return this.prezimeKorisnika;
   }

   public void setPrezimeKorisnika(java.lang.String prezimeKorisnika)
   {
      this.prezimeKorisnika = prezimeKorisnika;
   }

   public Korisnik(java.lang.Integer MSISDN, java.lang.String OIB,
         java.util.Date datumRodenja, java.lang.String imeKorisnika,
         java.lang.String prezimeKorisnika)
   {
      this.MSISDN = MSISDN;
      this.OIB = OIB;
      this.datumRodenja = datumRodenja;
      this.imeKorisnika = imeKorisnika;
      this.prezimeKorisnika = prezimeKorisnika;
   }

}