package bpm_vvg.sluzbazakorisnike;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MSISDN implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Numeracija MSISDN")
   private java.lang.Integer numeracijaMSISDN;
   @org.kie.api.definition.type.Label(value = "Serijski broj SIM karice")
   private java.lang.Integer ICC;

   public MSISDN()
   {
   }

   public java.lang.Integer getNumeracijaMSISDN()
   {
      return this.numeracijaMSISDN;
   }

   public void setNumeracijaMSISDN(java.lang.Integer numeracijaMSISDN)
   {
      this.numeracijaMSISDN = numeracijaMSISDN;
   }

   public java.lang.Integer getICC()
   {
      return this.ICC;
   }

   public void setICC(java.lang.Integer ICC)
   {
      this.ICC = ICC;
   }

   public MSISDN(java.lang.Integer numeracijaMSISDN, java.lang.Integer ICC)
   {
      this.numeracijaMSISDN = numeracijaMSISDN;
      this.ICC = ICC;
   }

}