package bpm_vvg.sluzbazakorisnike;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OdgovorKorisniku implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Status")
   private java.lang.Boolean status;

   public OdgovorKorisniku()
   {
   }

   public java.lang.Boolean getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.Boolean status)
   {
      this.status = status;
   }

   public OdgovorKorisniku(java.lang.Boolean status)
   {
      this.status = status;
   }

}