package bpm_vvg.sluzbazakorisnike;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RadnoMjesto implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Backoffice")
   private java.lang.String backoffice;
   @org.kie.api.definition.type.Label(value = "Pozivni Centar")
   private java.lang.String pozivniCentar;
   @org.kie.api.definition.type.Label(value = "Tehnicka Podrska")
   private java.lang.String tehnickaPodrska;
   @org.kie.api.definition.type.Label(value = "Prodajno Mjesto")
   private java.lang.String prodajnoMjesto;

   public RadnoMjesto()
   {
   }

   public java.lang.String getBackoffice()
   {
      return this.backoffice;
   }

   public void setBackoffice(java.lang.String backoffice)
   {
      this.backoffice = backoffice;
   }

   public java.lang.String getPozivniCentar()
   {
      return this.pozivniCentar;
   }

   public void setPozivniCentar(java.lang.String pozivniCentar)
   {
      this.pozivniCentar = pozivniCentar;
   }

   public java.lang.String getTehnickaPodrska()
   {
      return this.tehnickaPodrska;
   }

   public void setTehnickaPodrska(java.lang.String tehnickaPodrska)
   {
      this.tehnickaPodrska = tehnickaPodrska;
   }

   public java.lang.String getProdajnoMjesto()
   {
      return this.prodajnoMjesto;
   }

   public void setProdajnoMjesto(java.lang.String prodajnoMjesto)
   {
      this.prodajnoMjesto = prodajnoMjesto;
   }

   public RadnoMjesto(java.lang.String backoffice,
         java.lang.String pozivniCentar, java.lang.String tehnickaPodrska,
         java.lang.String prodajnoMjesto)
   {
      this.backoffice = backoffice;
      this.pozivniCentar = pozivniCentar;
      this.tehnickaPodrska = tehnickaPodrska;
      this.prodajnoMjesto = prodajnoMjesto;
   }

}