package bpm_vvg.sluzbazakorisnike;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ZahtjevMNP implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "ZahtjevMNP_ID")
   private java.lang.String zahtjevMNP_ID;
   @org.kie.api.definition.type.Label(value = "Korisnik Zahtjev")
   private bpm_vvg.sluzbazakorisnike.Korisnik korisnik_zahtjev;
   @org.kie.api.definition.type.Label(value = "MSISDN")
   private bpm_vvg.sluzbazakorisnike.MSISDN MSISDN_ID;
   @org.kie.api.definition.type.Label(value = "Status")
   private java.lang.Boolean status;

   public ZahtjevMNP()
   {
   }

   public java.lang.String getZahtjevMNP_ID()
   {
      return this.zahtjevMNP_ID;
   }

   public void setZahtjevMNP_ID(java.lang.String zahtjevMNP_ID)
   {
      this.zahtjevMNP_ID = zahtjevMNP_ID;
   }

   public bpm_vvg.sluzbazakorisnike.Korisnik getKorisnik_zahtjev()
   {
      return this.korisnik_zahtjev;
   }

   public void setKorisnik_zahtjev(
         bpm_vvg.sluzbazakorisnike.Korisnik korisnik_zahtjev)
   {
      this.korisnik_zahtjev = korisnik_zahtjev;
   }

   public bpm_vvg.sluzbazakorisnike.MSISDN getMSISDN_ID()
   {
      return this.MSISDN_ID;
   }

   public void setMSISDN_ID(bpm_vvg.sluzbazakorisnike.MSISDN MSISDN_ID)
   {
      this.MSISDN_ID = MSISDN_ID;
   }

   public java.lang.Boolean getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.Boolean status)
   {
      this.status = status;
   }

   public ZahtjevMNP(java.lang.String zahtjevMNP_ID,
         bpm_vvg.sluzbazakorisnike.Korisnik korisnik_zahtjev,
         bpm_vvg.sluzbazakorisnike.MSISDN MSISDN_ID, java.lang.Boolean status)
   {
      this.zahtjevMNP_ID = zahtjevMNP_ID;
      this.korisnik_zahtjev = korisnik_zahtjev;
      this.MSISDN_ID = MSISDN_ID;
      this.status = status;
   }

}