package bpm_vvg.sluzbazakorisnike;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ZatjevPretplata implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("ZahtjevID")
   private java.lang.String zahtjevID;
   @org.kie.api.definition.type.Label("Status")
   private java.lang.Boolean status;
   @org.kie.api.definition.type.Label("MSISDN")
   private bpm_vvg.sluzbazakorisnike.MSISDN MSISDN;

   @org.kie.api.definition.type.Label("Korisnik Zahtjev")
   private bpm_vvg.sluzbazakorisnike.Korisnik korisnik_zahtjev;

   @org.kie.api.definition.type.Label(value = "Agent koji je unosio")
   private java.lang.String agent_id;

   public ZatjevPretplata()
   {
   }

   public java.lang.String getZahtjevID()
   {
      return this.zahtjevID;
   }

   public void setZahtjevID(java.lang.String zahtjevID)
   {
      this.zahtjevID = zahtjevID;
   }

   public java.lang.Boolean getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.Boolean status)
   {
      this.status = status;
   }

   public bpm_vvg.sluzbazakorisnike.MSISDN getMSISDN()
   {
      return this.MSISDN;
   }

   public void setMSISDN(bpm_vvg.sluzbazakorisnike.MSISDN MSISDN)
   {
      this.MSISDN = MSISDN;
   }

   public bpm_vvg.sluzbazakorisnike.Korisnik getKorisnik_zahtjev()
   {
      return this.korisnik_zahtjev;
   }

   public void setKorisnik_zahtjev(
         bpm_vvg.sluzbazakorisnike.Korisnik korisnik_zahtjev)
   {
      this.korisnik_zahtjev = korisnik_zahtjev;
   }

   public java.lang.String getAgent_id()
   {
      return this.agent_id;
   }

   public void setAgent_id(java.lang.String agent_id)
   {
      this.agent_id = agent_id;
   }

   public ZatjevPretplata(java.lang.String zahtjevID, java.lang.Boolean status,
         bpm_vvg.sluzbazakorisnike.MSISDN MSISDN,
         bpm_vvg.sluzbazakorisnike.Korisnik korisnik_zahtjev,
         java.lang.String agent_id)
   {
      this.zahtjevID = zahtjevID;
      this.status = status;
      this.MSISDN = MSISDN;
      this.korisnik_zahtjev = korisnik_zahtjev;
      this.agent_id = agent_id;
   }

}